/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
  "github.com/rwxrob/opsapi/internal/api"
)

// AddPet - Add a new pet to the store
func AddPet(c *gin.Context) {
  api.Handle(c, "AddPet")
}

// DeletePet - Deletes a pet
func DeletePet(c *gin.Context) {
  api.Handle(c, "DeletePet")
}

// FindPetsByStatus - Finds Pets by status
func FindPetsByStatus(c *gin.Context) {
  api.Handle(c, "FindPetsByStatus")
}

// FindPetsByTags - Finds Pets by tags
// Deprecated
func FindPetsByTags(c *gin.Context) {
  api.Handle(c, "FindPetsByTags")
}

// GetPetById - Find pet by ID
func GetPetById(c *gin.Context) {
  api.Handle(c, "GetPetById")
}

// UpdatePet - Update an existing pet
func UpdatePet(c *gin.Context) {
  api.Handle(c, "UpdatePet")
}

// UpdatePetWithForm - Updates a pet in the store with form data
func UpdatePetWithForm(c *gin.Context) {
  api.Handle(c, "UpdatePetWithForm")
}

// UploadFile - uploads an image
func UploadFile(c *gin.Context) {
  api.Handle(c, "UploadFile")
}
