/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"github.com/rwxrob/opsapi/internal/api"
)

// CreateUser - Create user
func CreateUser(c *gin.Context) {
	api.Handle(c, "CreateUser")
}

// CreateUsersWithArrayInput - Creates list of users with given input array
func CreateUsersWithArrayInput(c *gin.Context) {
	api.Handle(c, "CreateUsersWithArrayInput")
}

// CreateUsersWithListInput - Creates list of users with given input array
func CreateUsersWithListInput(c *gin.Context) {
	api.Handle(c, "CreateUsersWithListInput")
}

// DeleteUser - Delete user
func DeleteUser(c *gin.Context) {
	api.Handle(c, "DeleteUser")
}

// GetUserByName - Get user by user name
func GetUserByName(c *gin.Context) {
	api.Handle(c, "GetUserByName")
}

// LoginUser - Logs user into the system
func LoginUser(c *gin.Context) {
	api.Handle(c, "LoginUser")
}

// LogoutUser - Logs out current logged in user session
func LogoutUser(c *gin.Context) {
	api.Handle(c, "LogoutUser")
}

// UpdateUser - Updated user
func UpdateUser(c *gin.Context) {
	api.Handle(c, "UpdateUser")
}
