swagger: "3.0"
info:
    title: Greetings
    description: API to greet people in different languages
    version: 0.1.0
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
paths: {}
definitions:
    
