openapi: "3.0"
info:
  description: A Greet API
  title: The Greet API
  version: 1.0.0
servers:
- url: https://localhost/v1
security:
- BasicAuth: []
paths:
  /greeting:
    get:
      description: "Returns \"Hello, :person\""
      responses:
        "200":
          description: Successful response
components:
  schemas: {}
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
